vich_uploader:
    db_driver: orm

    mappings:
        files:
            uri_prefix: /files
            upload_destination: '%kernel.project_dir%/var/files'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
